{% set name = "accimage" %}
{% set version = "0.2.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: '2122fa7ac3c570975fac47ad3d4d1fdbaefedf27430cba70efb674e83de3450b'

build:
  skip: true  # [not linux]
  number: 6
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libjpeg-turbo
    - intel-ipp
  run:
    - libjpeg-turbo
    - intel-ipp
    - python

test:
  imports:
    - accimage

about:
  home: https://github.com/pytorch/accimage
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: accimage is a fast PIL replacement leaning on libjpeg-turbo and Intel IPP.
  description: |
    accimage is a fast PIL replacement leaning on libjpeg-turbo and Intel IPP.

extra:
  recipe-maintainers:
    - willprice
