travis:
  secure:
    BINSTAR_TOKEN: GfZiI1w0IRrjtA2EfqhQ1mRVqdKv7vQm9X50eFAIC479U0dIF2734IJzu1wDCbMkcOg465YeIyKTCUv4mTkhkVYSLsLm9+/f5YNn9pqkrk1Ca8hC81Y/lJP17AUn8RSzXZ74UWwPFzd6WRfgZEiKlHYJpa/HW2u+dHBlXG1ZSnB8/gr78pX4VVpIpYC5FmBxD5osXVUCEW8RU8lcdOh1nObYZPYSsHWcw/OLvnNZdkJ9hYPQtPPsV8egTpMMYWoUkyEXvETPlSgOpW6rL6IOGBZZGrSmWtGjKyXOC254kifxMlJ7Cj72DCqkGaUSiBzbb75TBhywenEW2RX0VXEjjaeTfFEr2jezaQ36SmOpCVlSCXn4lFN9SkPJ8g3mScRC4n4Jecez2jknJUww9Os/R4sLxB2gRfTxQXULP46axy2wj+8xQsOJok2TDMPCUR7iFCzkkLSkC/dGH8E55WrUZKGa9jXv3P4Ejo21cB5femRhBpP3TffDG9VUr0FtkJvQzklDxG02L3A91dztbEHND6ELz695igzf+gyWJKE4Va2T/w5q74Rf/nXdH7t0xYi96U3ctQzeWmkDMXStUMMxdbRZkYGVOvnJyNR/Nf26JGuvAjtxzuGn9QZw7EVNCF/hwMwCMtz//WglqGH1E9Ke9xFOsi5Oegy2pOKnSGBW5Cg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
